general = {
    name = "Ubuntu PC";
    output_backend = "pa";
    mdns_backend = "avahi";
    port = 5000;
    udp_port_base = 6001;
    udp_port_range = 10;
    interpolation = "soxr";
    dbus_service_bus = "session";
    mpris_service_bus = "session";
};
pa = { application_name = "Ubuntu PC AirPlay"; };
metadata = { enabled = "yes"; include_cover_art = "yes"; };
