import assert from 'node:assert/strict';
import {mkdtemp, readFile, stat, rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import net from 'node:net';
const data=await mkdtemp(join(tmpdir(),'island-media-test-'));
const reserve=net.createServer();await new Promise(r=>reserve.listen(0,'127.0.0.1',r));
const port=reserve.address().port;await new Promise(r=>reserve.close(r));
Object.assign(process.env,{REMOTE_DATA:data,REMOTE_PORT:String(port),REMOTE_CDP_PORT:'1'});
const m=await import('../desktop/netflix-remote/server.mjs');
const interfaces={wifi:[{family:'IPv4',address:'10.23.4.8',netmask:'255.255.255.0',internal:false}]};
assert.equal(m.isLocal('10.23.4.7',interfaces,true),true);
assert.equal(m.isLocal('::ffff:10.23.4.7',interfaces,true),true);
assert.equal(m.isLocal('10.23.4.7',interfaces,false),false);
assert.equal(m.isLocal('10.23.5.7',interfaces,true),false);
assert.equal(m.isLocal('192.168.1.17',interfaces,true),false);
for(const address of ['8.8.8.8','100.64.0.1','169.254.1.2','10.23.4.999'])assert.equal(m.isLocal(address,interfaces,true),false);
assert.equal(m.normalizeNetflixUrl('https://www.netflix.com/title/123456'), 'https://www.netflix.com/watch/123456');
for(const url of ['https://evil.test/title/123456','https://netflix.com.evil.test/title/123456','http://www.netflix.com/title/123456','https://www.netflix.com:444/title/123456'])assert.throws(()=>m.normalizeNetflixUrl(url));
assert.equal(m.allowedTarget({type:'page',url:'https://www.netflix.com/watch/123456'}),true);
assert.equal(m.allowedTarget({type:'page',url:'https://www.netflix.com.evil.test/watch/123456'}),false);
const server=await m.start();
try{
 assert.equal(server.address().address,'127.0.0.1');
 const key=(await readFile(join(data,'remote-key'),'utf8')).trim();
 assert.match(key,/^[\w-]{32}$/);
 assert.equal((await stat(join(data,'remote-key'))).mode&0o777,0o600);
 assert.equal((await stat(data)).mode&0o777,0o700);
 const base=`http://127.0.0.1:${port}`;
 assert.equal((await fetch(base+'/api/state')).status,401);
 const state=await fetch(base+'/api/state',{headers:{Authorization:'Bearer '+key}});
 assert.equal(state.status,200);assert.equal((await state.json()).paired,true);
 assert.match(state.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);
 assert.equal((await fetch(base+'/api/state',{headers:{Authorization:'Bearer '+key,Origin:'https://evil.test'}})).status,403);
 assert.equal((await fetch(base+'/api/command',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({action:'run-shell',command:'anything'})})).status,400);
 assert.equal((await fetch(base+'/remote-key')).status,404);
 assert.equal((await fetch(base+'/fixture')).status,404);
 const page=await fetch(base+'/');assert.equal(page.status,200);assert.match(page.headers.get('content-security-policy'),/frame-ancestors 'none'/);
 assert.ok(!(await page.text()).includes(key));
 for(let i=0;i<20;i++)await fetch(base+'/api/state');
 assert.equal((await fetch(base+'/api/state')).status,429);
}finally{server.closeAllConnections();await new Promise(r=>server.close(r));await rm(data,{recursive:true,force:true});}
console.log('PASS Netflix remote: private fresh key, default loopback, same-subnet LAN policy, authentication, origin, route/action allowlists and rate limit');
