<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>IslandDesktop</AssemblyName>
    <RootNamespace>Island.Windows</RootNamespace>
    <Version>0.4.0-beta.2</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="NAudio" Version="2.2.1" /></ItemGroup>
  <ItemGroup><Compile Remove="Launcher.cs" /></ItemGroup>
<ItemGroup><Resource Include="Assets/owl.png" /></ItemGroup>
</Project>
